language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  on:
    branch: master
  provider: elasticbeanstalk
  access_key_id:
    $AWS_ACCESS_KEY_ID
  secret_access_key:
    $AWS_SECRET_ACCESS_KEY
  region: "eu-west-1"
  app: "gilded-rose-pairing-project"
  env: "gilded-rose-dev"
  bucket_name: "gilded-rose-pairing-project"
  skip_cleanup: true
