version: 2.1
orbs:
  android: circleci/android@1.0.3
jobs:
  unit:
    executor:
      name: android/android-machine
      resource-class: xlarge
    working_directory: ~/repo
    steps:
      - checkout
      - android/run-tests:
          working-directory: ~/repo/android
          test-command: ./gradlew testDebug
  android:
    executor:
      name: android/android-machine
      resource-class: xlarge
    working_directory: ~/repo
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          run-tests-working-directory: ~/repo/android
          post-emulator-launch-assemble-command: cd android; ./gradlew assembleDebugAndroidTest
          system-image: system-images;android-30;google_apis;x86

workflows:
  build_and_test:
    jobs:
      - unit
      - android